version: '3.8'

services:
  furuksong2-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    restart: unless-stopped
    networks:
      - nginxnet

networks:
  nginxnet:
    external: true
